apiVersion: storage.loft.sh/v1
kind: OSImage
metadata:
  name: ubuntu2404-20260826
spec:
  displayName: Ubuntu 24.04 LTS (Noble) - 2026-08-26
  owner:
    user: admin
  properties:
    metal3.vcluster.com/image-checksum: d0fe84bb5f80853425fa6be28e2c106f30104c3cfe8611933f2e65c9b63f0e30
    metal3.vcluster.com/image-checksum-type: sha256
    metal3.vcluster.com/image-url: https://cloud-images.ubuntu.com/noble/20260826/noble-server-cloudimg-amd64.img
